"use client";

import NavBar from "@/components/NavBar/NavBar";
import { createContext, useState } from "react";
import { useEffect } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { Abel } from "next/font/google";
import favicon from "../public/static/favicon.ico";

console.log("favicon", favicon);
const inter = Inter({ subsets: ["latin"] });
const abel = Abel({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const UserContext = createContext();

export default function RootLayout({ children }) {
  const [user, setUser] = useState({
    isLogged: false,
    checkLogin: false,
    showLoginOptions: false,
    name: "",
  });
  useEffect(() => {
    async function autoLogin() {
      const response = await fetch(
        "http://localhost:8000/api/users/autologin",
        {
          method: "GET",
          credentials: "include",
        }
      );
      if (response.status === 200) {
        setUser((prev) => ({ ...prev, user: user.name, isLogged: true }));
      } else {
        setUser((prev) => ({ ...prev, isLogged: false, checkLogin: true }));
      }
    }
    autoLogin();
  }, []);
  return (
    <html lang="en">
      <head>
        <title>ADEX Connect</title>
        <link rel="shortcut icon" href={favicon.src} />
        <script
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATrfv2ahP3hrMsAP8x5vwq3Hpy6qjGQgM&libraries=places"
          async
        />
      </head>
      <body className={abel.className}>
        <UserContext.Provider value={[user, setUser]}>
          <NavBar />
          {children}
        </UserContext.Provider>
      </body>
    </html>
  );
}
