"use client"
import NavBar from '@/components/NavBar/NavBar'
import { createContext,useState } from 'react';

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const dummyUser = {
  isLogged: false,
  name: "Eduardo"
}
export const UserContext = createContext();


export default function RootLayout({ children }) {
  const [user, setUser] = useState(
    {isLogged:false,
      name:'eee'
    });
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContext.Provider value={[user,setUser]}>
        <NavBar/>
        {children}
        </UserContext.Provider>
        </body>
    </html>
  )
}
