"use client"
import NavBar from '@/components/NavBar/NavBar'
import { createContext,useState } from 'react';
import { useEffect } from 'react';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const UserContext = createContext();


export default function RootLayout({ children }) {
  const [user, setUser] = useState(
    {isLogged:false,
      checkLogin:false,
      showLoginOptions:false,
      name:'',
    });
    useEffect(() => {
      async function autoLogin() {
        const response = await fetch("http://localhost:8000/api/users/autologin", {
          method: "GET",
          credentials: "include",
        });
        if (response.status === 200) {
          setUser((prev)=>({...prev,user: user.name,isLogged:true}));
        } else {
          setUser((prev)=>({...prev,isLogged:false,checkLogin:true}))
        }
      }
      autoLogin();
    }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContext.Provider value={[user,setUser]}>
        <NavBar/>
        {children}
        </UserContext.Provider>
        </body>
    </html>
  )
}
